### ISSUE TITLE
Fix State Updater

### ISSUE THREAD

**Issue by seanavery** [gear-sv/gear-nano#2]

**Comment by gWOLF3** [comment]
I believe the issue was 'e' event was not being passed to on query event handler. 

Please see my commit 6cadded7856056e68a55e74fa93fae93e17432e2 to verify if this solves the issue you were facing.

**Comment by seanavery** [comment]
Nice find on that. Somehow `e` was still defined even though I wasnt passing it in.. 

Also, I like the quickstart script.

Let me know if you are able to successfully query the db. You can do quick pings with the bitbus UI at `localhost:3010`. I am still getting key does not exist errors (even though the key does in fact exist).

You can use this contract to test. gear-nano init `5c4939405fdc8bdbbd3fec7da9c930e7605cea8aeada1177810f03ab763b445d`

**Comment by gWOLF3** [comment]
Cool, 

So the state/tx endpoints are working now. Tested in browser. 

Please reference the latest commit to see list of changes: 103cfa9e67d5f89a622a482310c41079fcd5d09d

<img width="1518" alt="Screen Shot 2019-10-18 at 5 41 50 PM" src="https://user-images.githubusercontent.com/34167140/67130281-cf00bd80-f1ce-11e9-8fe1-5ad05a614a31.png">
<img width="1518" alt="Screen Shot 2019-10-18 at 5 46 34 PM" src="https://user-images.githubusercontent.com/34167140/67130443-4898ab80-f1cf-11e9-84da-1520d6ab8e8d.png">


What's not working? 
- supply seems to not get updated, even though the 'mint' transaction is logged. 

I will look further and find out why. This has been helpful for me to understand better how things are working beneath the surface. Wanted to update on current status.

**Comment by gWOLF3** [comment]
The bug referenced here has been fixed by 2bc601cef9633bfda348c673f18ffd44b8ad73aa

Closing this issue, for other processor bugs, let's open new defects.
