### ISSUE TITLE
Invalid method params can break state

### ISSUE THREAD

**Issue by gWOLF3** [gear-sv/gear-nano#4]
What happened? 

Issue was found during the performance testing phase on contract ID # '3862ae21275acad4256c5e4a4a82b3662f53b3dfb9c96a29cb4df35b7c467b7a'

If we look inside our bus folder for the block that broke our state: '605216.json' , we see params such that the recipient address for 'transfer' was double string encoded: ' "s4": "[\"196Q9u4D7S7f43qTgWYgVFtL8ZJ9Km8Mj9\",30]" '.

**Comment by seanavery** [comment]
I think this should be solved with try catch around wasm call.

https://github.com/gear-sv/gear-nano/blob/master/bin/gearia.js#L120

**Comment by gWOLF3** [comment]
<img width="1671" alt="Screen Shot 2019-10-28 at 11 53 47 AM" src="https://user-images.githubusercontent.com/34167140/67694391-a2406900-f979-11e9-8d6d-58f9086d739c.png">

>Validated that this is indeed fixed.
